update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,31 +1,42 @@
-language: haskell
+# NB: don't set `language: haskell` here
 
-notifications:
-  email:
-    - gridaphobe@gmail.com
+env:
+ - TESTS=pos
+ - TESTS=neg
+ - TESTS=crash
+ - TESTS=text
+ - TESTS=bytestring
+ - TESTS=esop
+ - TESTS=vector-algorithms
+ - TESTS=hscolour
 
+# Note: the distinction between `before_install` and `install` is not important.
 before_install:
-  - git clone git://github.com/ucsd-progsys/liquid-fixpoint.git /tmp/fixpoint
-  - sudo apt-get update -qq
-  - sudo apt-get install ocaml camlidl
-  - pushd /tmp/fixpoint && cabal install -fz3mem && popd
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-1.18 ghc-7.8.3 ocaml camlidl
+ - export PATH=/opt/ghc/7.8.3/bin:/opt/cabal/1.18/bin:$PATH
+ - cabal update
+ - git clone git://github.com/ucsd-progsys/liquid-fixpoint.git /tmp/fixpoint
+ - pushd /tmp/fixpoint && cabal install -fz3mem && popd
 
 install:
  - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
-# Here starts the actual work to be performed for the package under
-# test; any command which exits with a non-zero exit code causes the
-# build to fail.
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
- # -v2 provides useful information for debugging
- - cabal install --enable-tests --enable-benchmarks -v2 -fz3mem
-
- - cd tests
- - PATH=$HOME/.cabal/bin:$PATH python regrtest.py -o '--smtsolver' -o 'z3mem'
- - cd ..
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - ./dist/build/test/test --pattern "$TESTS/"
  - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
- # tests that a source-distribution can be generated
- - cabal sdist
-
-# EOF
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
