Travis: Clear Cabal dependency cache on conflict

diff --git a/scripts/travis b/scripts/travis
--- a/scripts/travis
+++ b/scripts/travis
@@ -10,7 +10,7 @@ function loud {
   $@
 }
 
-# Source: https://github.com/travis-ci/travis-build/blob/fc4ae8a2ffa1f2b3a2f62533bbc4f8a9be19a8ae/lib/travis/build/script/templates/header.sh
+# Source: https://github.com/travis-ci/travis-build/blob/fc4ae8a2ffa1f2b3a2f62533bbc4f8a9be19a8ae/lib/travis/build/script/templates/header.sh#L104-L123
 RED="\033[31;1m"
 GREEN="\033[32;1m"
 RESET="\033[0m"
@@ -26,11 +26,12 @@ function travis_retry {
     result=$?
     set -e
     [ $result -eq 0 ] && break
+    result=$?
     count=$(($count + 1))
     sleep 1
   done
 
-  [ $count -eq 3 ] && {
+  [ $count -eq 4 ] && {
     echo "\n${RED}The command \"$@\" failed 3 times.${RESET}\n" >&2
   }
 
@@ -67,8 +68,15 @@ function pastebin {
 
 ## Testing Stages
 
-function setup_cabal {
-  loud travis_retry cabal update
+function clean_cache {
+  local smt="$1"
+
+  loud ghc-pkg unregister liquidhaskell --force || true
+  loud ghc-pkg unregister liquid-fixpoint --force || true
+  loud rm "$HOME/.cabal/bin/$smt" || true
+
+  loud find "$HOME/.cabal"
+  loud find "$HOME/.ghc"
 }
 
 function clone_fixpoint {
@@ -76,15 +84,27 @@ function clone_fixpoint {
 }
 
 function install_smt {
- local smt="$1"
- mkdir -p "$HOME/.cabal/bin"
- loud curl "http://goto.ucsd.edu/~gridaphobe/$smt" -o "$HOME/.cabal/bin/$smt"
- loud chmod a+x "$HOME/.cabal/bin/$smt"
+  local smt="$1"
+
+  mkdir -p "$HOME/.cabal/bin"
+  loud curl "http://goto.ucsd.edu/~gridaphobe/$smt" -o "$HOME/.cabal/bin/$smt"
+  loud chmod a+x "$HOME/.cabal/bin/$smt"
 }
 
 function install_cabal_deps {
-  loud travis_retry cabal install --only-dependencies --upgrade-dependencies --enable-tests -fbuild-external . /tmp/fixpoint
+  if ! _install_cabal_deps; then
+    echo " ==> Cabal install failed. Clearing dependency cache and retrying."
+    loud rm -rf "$HOME/.cabal"
+    loud rm -rf "$HOME/.ghc"
+    _install_cabal_deps
+  fi
+
   loud travis_retry cabal install -fbuild-external /tmp/fixpoint
+}
+
+function _install_cabal_deps {
+  loud travis_retry cabal update || return 1
+  loud travis_retry cabal install --only-dependencies --upgrade-dependencies --enable-tests -fbuild-external . /tmp/fixpoint || return 1
 }
 
 function do_build {
@@ -119,11 +139,6 @@ function test_source_pkg {
     echo "expected '$src_tgz' not found"
     return 1
   fi
-}
-
-function do_cleanup {
-  loud ghc-pkg unregister liquidhaskell --force || true
-  loud ghc-pkg unregister liquid-fixpoint --force || true
 }
 
 ## Run Test Stage
